//! Property tests: whatever UDP does to the input stream, the confirmed frames
//! must converge on the same simulation.
//!
//! The unit tests in `session.rs` cover specific delivery patterns that were
//! easy to reason about. This file covers the ones nobody thought of: arbitrary
//! reordering, arbitrary duplication, and arbitrary delay, generated by
//! proptest and shrunk to a minimal counter-example when something breaks.
//!
//! The invariant under test is the one the whole design rests on:
//!
//! > Once every input for frames `0..N` has been delivered -- in any order, any
//! > number of times, at any time -- the session's state at frame `N` is
//! > identical to a session that received them all in order up front.
//!
//! Loss is modelled as delay, which is what the protocol actually turns it
//! into: every `InputBatch` repeats the last eight inputs, so a dropped
//! datagram means a frame arrives later, not never. A frame that is *never*
//! delivered is a disconnection, and the timeout handles that instead.

use proptest::prelude::*;
use rollback_core::{
    testing::CounterSim, AdvanceOutcome, Frame, PlayerHandle, PlayerInput, RollbackSession,
    SessionConfig, Simulation,
};

const REDUNDANCY: usize = 8;

fn config() -> SessionConfig {
    SessionConfig::default()
}

/// The reference: every remote input known before the first frame, so nothing
/// is ever predicted and nothing is ever rolled back.
fn reference(remote: &[PlayerInput], local: &[PlayerInput]) -> (u64, Frame) {
    let mut session =
        RollbackSession::new(CounterSim::default(), config(), PlayerHandle::P1).unwrap();
    session.add_remote_inputs(1, remote).unwrap();
    for &input in local {
        session.add_local_input(input).unwrap();
        match session.advance().unwrap() {
            AdvanceOutcome::Advanced { .. } => {}
            AdvanceOutcome::Stalled { .. } => unreachable!("nothing to wait for"),
        }
    }
    assert_eq!(session.stats().rollbacks, 0, "the reference must be clean");
    (session.simulation().checksum(), session.current_frame())
}

/// One `InputBatch` as the runner would build it: the last eight local inputs
/// of the sender, ending at `through`.
fn batch(remote: &[PlayerInput], through: usize) -> (Frame, Vec<PlayerInput>) {
    let end = (through + 1).min(remote.len());
    let start = end.saturating_sub(REDUNDANCY);
    // Remote frame numbering starts at 1: frame 0 is the input-delay pre-fill.
    ((start + 1) as Frame, remote[start..end].to_vec())
}

proptest! {
    #![proptest_config(ProptestConfig { cases: 96, ..ProptestConfig::default() })]

    /// Batches arrive late, out of order and more than once.
    #[test]
    fn arbitrary_delivery_converges_on_the_reference(
        remote in prop::collection::vec(any::<u16>().prop_map(|v| PlayerInput(v & 0x03FF)), 60..200),
        local_seed in any::<u16>(),
        delays in prop::collection::vec(0usize..7, 60..200),
        duplicates in prop::collection::vec(any::<bool>(), 60..200),
    ) {
        let local: Vec<PlayerInput> = (0..remote.len())
            .map(|i| PlayerInput(local_seed.wrapping_add(i as u16 * 13) & 0x03FF))
            .collect();
        let (expected_checksum, expected_frame) = reference(&remote, &local);

        let mut session =
            RollbackSession::new(CounterSim::default(), config(), PlayerHandle::P1).unwrap();

        // Batches waiting to be delivered, keyed by the tick they arrive on.
        let mut inflight: Vec<(usize, Frame, Vec<PlayerInput>)> = Vec::new();
        let mut sent_through = 0usize;
        let mut tick = 0usize;

        // Run for long enough that even the most delayed batch lands, plus
        // slack for the stalls that deep delays cause.
        let budget = local.len() * 4 + 64;
        while session.current_frame() < expected_frame && tick < budget {
            // The peer sends one batch per tick, until it runs out of inputs.
            if sent_through < remote.len() {
                let (start, inputs) = batch(&remote, sent_through);
                let delay = delays.get(sent_through).copied().unwrap_or(0);
                inflight.push((tick + delay, start, inputs.clone()));
                if duplicates.get(sent_through).copied().unwrap_or(false) {
                    // A duplicate, arriving at some other time.
                    inflight.push((tick + delay + 2, start, inputs));
                }
                sent_through += 1;
            }

            // Deliver everything due. `retain` keeps the rest; the order here
            // is the arrival order, which is deliberately not sorted.
            let due: Vec<(Frame, Vec<PlayerInput>)> = inflight
                .iter()
                .filter(|(at, _, _)| *at <= tick)
                .map(|(_, start, inputs)| (*start, inputs.clone()))
                .collect();
            inflight.retain(|(at, _, _)| *at > tick);
            for (start, inputs) in due {
                session.add_remote_inputs(start, &inputs).unwrap();
            }

            if !session.would_stall() {
                let index = session.current_frame().max(0) as usize;
                let input = local.get(index).copied().unwrap_or(PlayerInput::NEUTRAL);
                session.add_local_input(input).unwrap();
                let _ = session.advance().unwrap();
            }
            tick += 1;
        }

        // Flush anything still in flight, which forces the last corrections.
        for (_, start, inputs) in inflight {
            session.add_remote_inputs(start, &inputs).unwrap();
        }

        prop_assert_eq!(
            session.current_frame(),
            expected_frame,
            "the session did not reach the reference frame within its budget"
        );
        prop_assert_eq!(
            session.simulation().checksum(),
            expected_checksum,
            "converged on a different state than the in-order reference"
        );
    }

    /// Delivering the same batch many times must be a no-op after the first.
    #[test]
    fn repeated_delivery_is_idempotent(
        remote in prop::collection::vec(any::<u16>().prop_map(PlayerInput), 20..60),
        repeats in 1usize..6,
    ) {
        let mut session =
            RollbackSession::new(CounterSim::default(), config(), PlayerHandle::P1).unwrap();
        for _ in 0..20 {
            session.add_local_input(PlayerInput(1)).unwrap();
            let _ = session.advance().unwrap();
        }

        session.add_remote_inputs(1, &remote).unwrap();
        let after_first = (
            session.simulation().checksum(),
            session.stats().rollbacks,
            session.confirmed_frame(),
        );
        for _ in 0..repeats {
            session.add_remote_inputs(1, &remote).unwrap();
        }
        prop_assert_eq!(
            (
                session.simulation().checksum(),
                session.stats().rollbacks,
                session.confirmed_frame()
            ),
            after_first
        );
    }

    /// The session must never advance past the prediction limit, whatever the
    /// peer does. This is what bounds the state buffer.
    #[test]
    fn prediction_never_exceeds_the_configured_limit(
        silence_after in 0usize..40,
        frames in 40usize..120,
    ) {
        let config = config();
        let mut session =
            RollbackSession::new(CounterSim::default(), config, PlayerHandle::P1).unwrap();

        for f in 0..frames {
            if f < silence_after {
                session
                    .add_remote_inputs(f as Frame + 1, &[PlayerInput(7)])
                    .unwrap();
            }
            if session.would_stall() {
                continue;
            }
            session.add_local_input(PlayerInput(3)).unwrap();
            let _ = session.advance().unwrap();
            prop_assert!(
                session.prediction_depth() <= u32::from(config.prediction_limit),
                "speculated {} frames ahead, limit is {}",
                session.prediction_depth(),
                config.prediction_limit
            );
        }
    }

    /// Confirmed frames are monotonic: once a frame is confirmed it stays
    /// confirmed, no matter what arrives afterwards.
    #[test]
    fn the_confirmed_frontier_never_moves_backwards(
        remote in prop::collection::vec(any::<u16>().prop_map(PlayerInput), 40..120),
        order in prop::collection::vec(0usize..40, 40..120),
    ) {
        let mut session =
            RollbackSession::new(CounterSim::default(), config(), PlayerHandle::P1).unwrap();
        let mut highest = session.confirmed_frame();

        for (i, &pick) in order.iter().enumerate() {
            if !session.would_stall() {
                session.add_local_input(PlayerInput(i as u16)).unwrap();
                let _ = session.advance().unwrap();
            }
            let at = pick.min(remote.len().saturating_sub(1));
            let (start, inputs) = batch(&remote, at);
            session.add_remote_inputs(start, &inputs).unwrap();

            let now = session.confirmed_frame();
            prop_assert!(
                now >= highest,
                "confirmed frame went backwards: {} -> {}",
                highest,
                now
            );
            highest = now;
        }
    }
}
